// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-SeBGqsxGgOp3T4320WIM1bC2X6ZPeI',
    appId: '1:662873475909:web:70daed7ce4adb84a6a0c2c',
    messagingSenderId: '662873475909',
    projectId: 'food-truck-inventory',
    authDomain: 'food-truck-inventory.firebaseapp.com',
    storageBucket: 'food-truck-inventory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE4XYfGoBpy1bvwOkNM_OxMKyQMGO09rg',
    appId: '1:662873475909:android:0784386f7fc883256a0c2c',
    messagingSenderId: '662873475909',
    projectId: 'food-truck-inventory',
    storageBucket: 'food-truck-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp4H1BxVPtXR84fZ1ZWA7q-BgSJwndEQo',
    appId: '1:662873475909:ios:4c5325aee7b0a6b56a0c2c',
    messagingSenderId: '662873475909',
    projectId: 'food-truck-inventory',
    storageBucket: 'food-truck-inventory.firebasestorage.app',
    iosClientId: '662873475909-9v7enr5qa8273ilad61ama78njmjpphr.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodTruckInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp4H1BxVPtXR84fZ1ZWA7q-BgSJwndEQo',
    appId: '1:662873475909:ios:4c5325aee7b0a6b56a0c2c',
    messagingSenderId: '662873475909',
    projectId: 'food-truck-inventory',
    storageBucket: 'food-truck-inventory.firebasestorage.app',
    iosClientId: '662873475909-9v7enr5qa8273ilad61ama78njmjpphr.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodTruckInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ-SeBGqsxGgOp3T4320WIM1bC2X6ZPeI',
    appId: '1:662873475909:web:7e3e552b6aeee6b46a0c2c',
    messagingSenderId: '662873475909',
    projectId: 'food-truck-inventory',
    authDomain: 'food-truck-inventory.firebaseapp.com',
    storageBucket: 'food-truck-inventory.firebasestorage.app',
  );
}
